# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d9279ddb4ffc4d777ce26c3183987d9919e59682080533497f620d5d38ef3e9838460ce4904a684eeb481436ff29b621ecac0ba017905fa15f3c1c72af2e4e0

test:
  secret_key_base: 228046c754602d5c76953c20c150f3571b1a8f2ee5b522c323e0d0404f69b98ace6d5043968e3fbbe0c3d581714ff448a41f1ebf5d779fb3d1eafeea04c14b3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
